meta_product_name: "STRAVEL"
meta_title: "STRAVEL - Find a cool night out together!"
meta_description: "STRAVEL makes it easy to meet likeminded people for a great night out together"
meta_image: "stravel-og-image.png" # should exist in `app/assets/images/`
